<a href="https://colab.research.google.com/github/Jean030/Publish/blob/dependabot%2Fnpm_and_yarn%2Fchokidar-4.0.3/0_PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tutorial

### DOTE6698: Machine Learning for Business II (Term 3, 2025/26)



# Pytorch

This tutorial is adapted from the Tutorial of [CS224N: Natural Language Processing with Deep Learning of Stanford University](https://colab.research.google.com/drive/13HGy3-uIIy1KD_WFhG4nVrxJC-3nUUkP?usp=sharing) and the Tutorial of [DSME 6635: Artificial Intelligence for Business Research of CUHK](https://colab.research.google.com/drive/1Yg5q5v2CKNwPuaNAieg7ENDdA8Tn3wux)

In this notebook, we will have a basic introduction to [`PyTorch`](https://pytorch.org/). Below are some additional resources useful for learning PyTorch basics:

* Official PyTorch Documentation on [Deep Learning with PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by Soumith Chintala
* ["Word Window Classification" tutorial notebook](https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1204/materials/ww_classifier.ipynb) by Matt Lamm, from Winter 2020 offering of CS224N


In [ ]:
import torch
import torch.nn as nn

# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

We are all set to start our tutorial. Let's dive in!

## 1. Tensors

**Tensors** are PyTorch's most basic building block. Each tensor is a multi-dimensional matrix; for example, a 256x256 square image might be represented by a `3x256x256` tensor, where the first dimension represents color (i.e., channel). Here's how to create a tensor:

<img src="https://tensorflownet.readthedocs.io/en/latest/_static/tensor-naming.png"></img>

### 1.1. Creating tensors

In [ ]:
list_of_lists = [
  [[1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]],
  [[10, 11, 12],
   [13, 14, 15],
    [16, 17, 18]],
]

print(list_of_lists)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]


In [ ]:
# Initializing a tensor
data = torch.tensor(list_of_lists)
print(data)
print(data.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
torch.Size([2, 3, 3])


You can also inter-convert tensors with **NumPy arrays**:

In [ ]:
import numpy as np

arr = np.array(list_of_lists)
print("This is a np.ndarray", arr)

# numpy.ndarray --> torch.Tensor:
data = torch.from_numpy(arr)
print("This is a torch.tensor", data)
print("Location of the tensor in memory", data.data_ptr())

# change in the tensor will reflect in the numpy array
data[0][0][0] = 1000
print("This is a torch.tensor", data)
print("This is a np.ndarray", arr)

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray", new_arr)
# change in the numpy array will also reflect in the tensor

This is a np.ndarray [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
This is a torch.tensor tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Location of the tensor in memory 134408416
This is a torch.tensor tensor([[[1000,    2,    3],
         [   4,    5,    6],
         [   7,    8,    9]],

        [[  10,   11,   12],
         [  13,   14,   15],
         [  16,   17,   18]]])
This is a np.ndarray [[[1000    2    3]
  [   4    5    6]
  [   7    8    9]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]]
This is a np.ndarray [[[1000    2    3]
  [   4    5    6]
  [   7    8    9]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]]


Each tensor has a **data type**: the major data types you'll need to worry about are:
1. floats (`torch.float32`);
2. integers (`torch.int`).

You can specify the data type explicitly when you create the tensor:

In [ ]:
# Initializing a tensor without explicit data type
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)
print(data.dtype)

tensor([[0, 1],
        [2, 3],
        [4, 5]])
torch.int64


In [ ]:
# Initializing a tensor without explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)
print(data.dtype)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])
torch.float32


In [ ]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)
print(data.dtype)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
torch.float32


For decimal numbers, `torch.float32` is the default data type of PyTorch and provides approximately 7 decimal digits of precision. However, when you need higher precision (e.g., scientific computing), you can specify the data type as 64-bit floating point (i.e.,`torch.float64`), which provides approximately 15 decimal digits of precision.

In [ ]:
# Initializing a tensor with float32 vs float64
data = torch.tensor([
                     [0.111111111232, 1],
                     [2, 3.23132],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)
print(data[0][0].item())

tensor([[0.1111, 1.0000],
        [2.0000, 3.2313],
        [4.0000, 5.0000]])
0.1111111119389534


In [ ]:
# Initializing a tensor with float32 vs float64
data = torch.tensor([
                     [0.111111111232, 1],
                     [2, 3.23132],
                     [4, 5]
                    ], dtype=torch.float64)
print(data)
print(data[0][0].item())

tensor([[0.1111, 1.0000],
        [2.0000, 3.2313],
        [4.0000, 5.0000]], dtype=torch.float64)
0.111111111232


Utility functions also exist to create tensors with given shapes and contents:

In [ ]:
zeros = torch.zeros(2, 5)  # a tensor of all zeros
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
ones = torch.ones(3, 4)   # a tensor of all ones
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
rr = torch.arange(1, 10) # range from [1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # Shape: (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # Shape: (2, 4)

print("A is", a)
print("B is", b)
print("The product is", a.matmul(b))
print("The other product is", a @ b) # both are for matrix multiplication

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [ ]:
# Before multiplication, remember that the shape should match with each other
t = torch.tensor([[1,2,3],[3,4,5]])
v = torch.tensor([[1,1,1]])

print(t.shape)
print(v.shape)

torch.Size([2, 3])
torch.Size([1, 3])


In [ ]:
print(t @ v)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 1x3)

In [ ]:
print(t @ v.T)

tensor([[ 6],
        [12]])


### 1.2. Shape of tensors
The **shape** of a matrix (which can be accessed by `.shape`) is defined as the dimensions of the matrix. Here are some examples:

<img width="70%" src="https://githubraw.cdn.bcebos.com/PaddlePaddle/FluidDoc/develop/doc/paddle/guides/images/Tensor_2.0.png"> </img>

In [ ]:
ts_1d = torch.tensor([2,3,4],dtype=float)
print(ts_1d.shape)
print(ts_1d)
print()

ts_2d = torch.arange(1, 7).reshape(2,3)
print(ts_2d.shape)
print(ts_2d)
print()

ts_3d = torch.arange(1,21).reshape(2,2,5)
print(ts_3d.shape)
print(ts_3d)

torch.Size([3])
tensor([2., 3., 4.], dtype=torch.float64)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])

torch.Size([2, 2, 5])
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])


**Think of two boxes stacked together**

<img width="60%" style="float:center" src="https://githubraw.cdn.bcebos.com/PaddlePaddle/FluidDoc/develop/doc/paddle/guides/images/Axis_2.0.png?raw=true"> </img>





In [ ]:
matr_4d = torch.ones((2,3,4,5))
print(matr_4d)
print(matr_4d.shape)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])
torch.Size([2, 3, 4, 5])


**Reshaping** tensors can be used to make batch operations easier (more on that later), but be careful that the data is reshaped in the order you expect:

In [ ]:
rr = torch.arange(1, 16)
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print("The location of tensor is", rr.storage().data_ptr()) # returns the memory address of the tensor's underlying storage
print()

rr = rr.view(5, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)
print("The location of tensor is", rr.storage().data_ptr())
print()

rr = rr.view(3, 5)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)
print("The location of tensor is", rr.storage().data_ptr())

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
The location of tensor is 136104512

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
The location of tensor is 136104512

After reshaping, the shape is currently torch.Size([3, 5])
The contents are currently tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])
The location of tensor is 136104512


In [ ]:
rr = torch.randn(2,8,1)
print(rr, rr.shape)
print("The location of tensor is", rr.storage().data_ptr())
print()

rr = rr.transpose(0,-1) # Transpose the tensor along the 0th and last dimension
print(rr,rr.shape)
print("The location of tensor is", rr.storage().data_ptr())
print()

# rr = rr.view(4,4,1)  # Raises an error!
# rr = rr.contiguous().view(4,4,1) # Works!
# print("The location of tensor is", rr.storage().data_ptr())

rr = rr.reshape(4,4,1) # Works! Make a contiguous copy of the tensor and then reshape it
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print("The location of tensor is", rr.storage().data_ptr())
print()

rr = rr.reshape(4,4) # reshape the contiguous tensor, no copy is made
print("The shape is currently", rr.shape)
print("The location of tensor is", rr.storage().data_ptr())

tensor([[[-0.2468],
         [ 0.4308],
         [-0.7105],
         [-0.6873],
         [-0.0367],
         [-1.0499],
         [-1.0356],
         [ 1.5644]],

        [[-1.2028],
         [ 0.7124],
         [-1.0845],
         [ 0.6578],
         [ 0.8566],
         [-1.5944],
         [ 0.5695],
         [ 2.1218]]]) torch.Size([2, 8, 1])
The location of tensor is 136103936

tensor([[[-0.2468, -1.2028],
         [ 0.4308,  0.7124],
         [-0.7105, -1.0845],
         [-0.6873,  0.6578],
         [-0.0367,  0.8566],
         [-1.0499, -1.5944],
         [-1.0356,  0.5695],
         [ 1.5644,  2.1218]]]) torch.Size([1, 8, 2])
The location of tensor is 136103936

The shape is currently torch.Size([4, 4, 1])
The contents are currently tensor([[[-0.2468],
         [-1.2028],
         [ 0.4308],
         [ 0.7124]],

        [[-0.7105],
         [-1.0845],
         [-0.6873],
         [ 0.6578]],

        [[-0.0367],
         [ 0.8566],
         [-1.0499],
         [-1.5944]],

      

| Feature                 | `view`                              | `reshape`                           |
|-------------------------|--------------------------------------|--------------------------------------|
| **Memory efficiency**   | Always uses the same memory         | May allocate new memory             |
| **Contiguity required** | Yes                                 | No                                  |
| **Speed**               | Faster (no data movement)           | Slower (if data rearrangement needed) |
| **Flexibility**         | Requires contiguous tensors         | Works with any tensor layout        |

### 1.3. Vectorized operations

One of the reasons why we use **tensors** is *vectorized operations*: operations that be conducted in parallel over a particular dimension of a tensor.

In [ ]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("Data is:", data)

# We can perform operations like *sum* along the dimension 0 ...
print("Taking the sum over columns:")
print(data.sum(dim=0))

# or along the dimension 1
print("Taking the sum over rows:")
print(data.sum(dim=1))

# Other operations are available:
print("Taking the stdev over rows:")
print(data.std(dim=1))


Data is: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
Taking the sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
Taking the sum over rows:
tensor([ 28.,  77., 126., 175., 224.])
Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [ ]:
data.sum()

tensor(630.)

**Quiz**

Write code that creates a `torch.tensor` with the following contents:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

Now compute the average of each row (`.mean()`) and each column.

What's the shape of the results?



In [ ]:
# Enter your code here


### 1.4. Indexing

You can access arbitrary elements of a tensor using the `[]` operator.

In [ ]:
# create a tensor with values from 1 to 15 and shape (5, 3)
matr = torch.arange(1, 16).view(5, 3)
print(matr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [ ]:
# let's say we want to get an element from the tensor
# if you simply put one index, you will get a row
matr[0,1]

tensor(2)

In [ ]:
# get the first row
matr[0,:]

tensor([1, 2, 3])

In [ ]:
# get the first column
matr[:,0]

tensor([ 1,  4,  7, 10, 13])

In [ ]:
# get the first three rows
matr[0:3,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# get the first two columns
matr[:,0:2]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])

In [ ]:
# get a submatrix of the tensor (first three rows and first two columns)
matr[0:3,0:2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

We can get a `Python` scalar value from a tensor with `item()`.

In [ ]:
# get the value at the first row and third column
# item() is used to get the value as a Python number
# otherwise, it will return a tensor
matr[0,1].item()

2

In [ ]:
# let's see the difference between putting one index and two indices in the tensor
print(matr[0:3, 2]) # get the third column of the first three rows
print(matr[0:3][2]) # get the third (last) row of the first three rows you extracted from the tensor

tensor([3, 6, 9])
tensor([7, 8, 9])


In [ ]:
# Along the first dimension, get the first, third, and fifth rows
matr[[0,2,4],:]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])

We can also index into multiple dimensions with `:`.

In [ ]:
# Initialize a more complex tensor
# matrix is the 1st dimension, row is the 2nd dimension, and column is the 3rd dimension
x = torch.tensor([
                    [[1, 2], [3, 4]], # First matrix
                    [[5, 6], [7, 8]], # Second matrix
                    [[9, 10], [11, 12]] # Third matrix
                     ])

In [ ]:
# get the shape of the tensor to understand the dimensions
x.shape

torch.Size([3, 2, 2])

In [ ]:
# Get the first column in each matrix in the tensor
x[:,:,0]

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])

In [ ]:
# Access the 0th element, which is the first matrix
x[0] # or x[0,:,:]

tensor([[1, 2],
        [3, 4]])

In [ ]:
x[:, 0] # note the index is not specified for the last dimension here, equivalent to x[:, 0, :]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [ ]:
x[:, :, :]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

We can also access arbitrary elements in each dimension.

In [ ]:
# Let's access the 0th and 1st elements, each twice
i = torch.tensor([0, 0, 1, 1])
x[i] # This is equivalent to x[[0, 0, 1, 1], :, :]

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[5, 6],
         [7, 8]]])

In [ ]:
# Let's undertand the following indexing
i = torch.tensor([1, 2])
j = torch.tensor([0])

# what do you expect to get?
# check the result to see if you are correct
x[i, j]

**Exercise:**

Write code that creates a `torch.tensor` with the following contents:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

How do you get the first column? The first row?



In [ ]:
# Enter your code here


## 2. Autograd: Automatic Differentiation

Pytorch is well-known for its automatic differentiation feature.

(Optional: if you're interested, check the following two notebooks to see why this automatic differentiation feature is important for our ML/DL algorithms:
- [Gradient Descent](https://colab.research.google.com/drive/1Ees_u-BRcGB0JBfx9N7vOhltOu9coA8Z): how we can use gradients to optimize our models
- [Chain Rule](https://colab.research.google.com/drive/1NahSzdbkV4D8GWa-avmZdm8kDHkaNndY): how we can use the chain rule to calculate the gradients of complex functions)

To compute those gradients, PyTorch has a built-in differentiation engine called `torch.autograd`. It supports automatic computation of gradient for any computational graph. We can call the `backward()` method to ask `PyTorch` to calculate the gradients, which are then stored in the `grad` attribute.

In [ ]:
# Create an example tensor
# requires_grad parameter tells PyTorch to store gradients
x = torch.tensor([2.], requires_grad=True)

# Print the gradient if it is calculated
# Currently None since x is a scalar
pp.pprint(x.grad)

None


In [ ]:
# Calculating the gradient of z with respect to x
x = torch.tensor([2.], requires_grad=True)
y = x * x * 3 # 3x^2
z = 2 * y
z.backward() # backpropagate error from z based on the computation graph embedded in z
pp.pprint(y.grad) # d(z)/d(y) = d(2*y)/d(y) = 2
pp.pprint(x.grad) # d(z)/d(x) = d(z)/d(y) * d(y)/d(x) = 2 * d(3x^2)/d(x) = 2 * 6x = 24

print(z.grad_fn) # a function that references the operation that created the tensor z

None
tensor([24.])


<ipython-input-83-de323e758eb0>:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  pp.pprint(y.grad) # d(z)/d(y) = d(2*y)/d(y) = 2


Here `x` is a leaf tensor (created directly), so its gradient is explicitly stored in `x.grad`. However, `y` is a non-leaf tensor (result of an operation). By default, PyTorch does not retain gradients for non-leaf tensors unless explicitly requested using `.retain_grad()`.

In [ ]:
# Calculating the gradient of z with respect to x, y
x = torch.tensor([2.], requires_grad=True)
y = x * x * 3 # 3x^2
y.retain_grad() # y.grad would be none without this line
z = 2 * y
z.backward() # backpropagate error from z based on the computation graph embedded in z
pp.pprint(y.grad) # d(z)/d(y) = d(2*y)/d(y) = 2
pp.pprint(x.grad) # d(z)/d(x) = d(z)/d(y) * d(y)/d(x) = 2 * d(3x^2)/d(x) = 2 * 6x = 24

print(z.grad_fn) # a function that references the operation that created the tensor z

tensor([2.])
tensor([24.])


In a forward pass, `autograd` does two things simultaneously:

- run the requested operation to compute a resulting tensor
- maintain the operation’s gradient function in the DAG.

The backward pass kicks off when `.backward()` is called on the DAG root. `autograd` then:

- computes the gradients from each `.grad_fn`,
- accumulates them in the respective tensor’s `.grad` attribute
- using the chain rule, propagates all the way to the leaf tensors.

Let's run backprop from a different tensor again to see what happens.

In [ ]:
z_new = 3 * x # 3x
z_new.backward()
pp.pprint(x.grad) # d(z_new)/d(x) = d(3x)/d(x) = 3
# The gradient is accumulated ! So, we need to zero it out before the next calculation

tensor([27.])


We can see that the `x.grad` is updated to be **the sum of the gradients calculated so far**. When we run backprop in a neural network, we sum up all the gradients for a particular neuron before making an update. This is exactly what is happening here! This is also the reason why we need to run `zero_grad()` in every training iteration (more on this later). Otherwise our gradients would keep building up from one training iteration to the other, which would cause our updates to be wrong.

## 3. Neural Network Module (`torch.nn`)

So far we have looked into the tensors, their properties and basic operations on tensors. These are especially useful to get familiar with if we are building the layers of our network from scratch. Moving forward, we will first use predefined blocks in the `torch.nn` module of `PyTorch`. Then we will put together these blocks to create complex networks. Let's start by importing this module with an alias so that we don't have to type `torch` every time we use it.

In [ ]:
import torch.nn as nn

### 3.1. Linear Layer
We can use `nn.Linear(H_in, H_out)` to create a a linear layer. This will take a matrix of `(N, *, H_in)` dimensions and output a matrix of `(N, *, H_out)`.

The `*` denotes that there could be arbitrary number of dimensions in between. These additional dimensions are typically treated as independent examples or data "features" that are processed in parallel with the batch size. This can represent things like:
- Different independent features in structured data.
- Time steps or sequences in time series data.
- Multiple channels in the case of images.

The linear layer performs the operation `Ax+b`, where `A` and `b` are initialized randomly. If we don't want the linear layer to learn the bias parameters, we can initialize our layer with `bias=False`.

In [ ]:
# Create the inputs
input = torch.ones(2,3,4) # 2 samples, 3 channels, 4 input features
# N is the batch size, * means any number of additional dimensions (in this case 3), H_in is the input size, H_out is the output size

# Make a linear layers transforming N,*,H_in dimensinal inputs to N,*,H_out
# dimensional outputs
linear = nn.Linear(4, 2) # 4 input features, 2 output features
linear_output = linear(input)
linear_output

tensor([[[-0.4418,  0.5653],
         [-0.4418,  0.5653],
         [-0.4418,  0.5653]],

        [[-0.4418,  0.5653],
         [-0.4418,  0.5653],
         [-0.4418,  0.5653]]], grad_fn=<ViewBackward0>)

In [ ]:
linear_output.shape

torch.Size([2, 3, 2])

In [ ]:
# let's see the weights and biases of the linear layer
[(parameter, parameter.shape) for parameter in linear.parameters()]
# We will apply these weights and biases to the input to get the output over each channel
# so to optimize the parameters of the linear layer, we actually use batch_size * num_channels observations with 4 features each

[(Parameter containing:
  tensor([[ 0.0042,  0.4746, -0.0351,  0.4885],
          [ 0.4338, -0.4341, -0.3456,  0.0959]], requires_grad=True),
  torch.Size([2, 4])),
 (Parameter containing:
  tensor([0.2463, 0.1454], requires_grad=True),
  torch.Size([2]))]

Data of shape:
- Input: [batch_size, *, feature_dim] # 4
- Output: [batch_size, *, output_dim] # 2

Linear layer of shape: (feature_dim, output_dim) # broadcast the weights over the batch and * dimensions

### 3.2. Other Module Layers
There are several other preconfigured layers in the `nn` module. Some commonly used examples are `nn.BatchNorm1d`, `nn.BatchNorm2d`, `nn.Conv2d`, `nn.ConvTranspose2d`, `nn.MaxPool2d` and `nn.Upsample` among many others. We will learn more about these as we progress in the course. For now, the only important thing to remember is that we can treat each of these layers as plug and play components: we will be providing the required dimensions and `PyTorch` will take care of setting them up.

### 3.3. Activation Function Layer
We can also use the `nn` module to apply activation functions to our tensors. Activation functions are used to add non-linearity to our network. Some examples of activation functions are `nn.ReLU()`, `nn.Sigmoid()` and `nn.LeakyReLU()`. Activation functions operate on each element seperately, so the shape of the tensors we get as an output is the same as the ones we pass in.

In [ ]:
linear_output

tensor([[[ 1.1785, -0.1046],
         [ 1.1785, -0.1046],
         [ 1.1785, -0.1046]],

        [[ 1.1785, -0.1046],
         [ 1.1785, -0.1046],
         [ 1.1785, -0.1046]]], grad_fn=<ViewBackward0>)

In [ ]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.7647, 0.4739],
         [0.7647, 0.4739],
         [0.7647, 0.4739]],

        [[0.7647, 0.4739],
         [0.7647, 0.4739],
         [0.7647, 0.4739]]], grad_fn=<SigmoidBackward0>)

### 3.4. Putting the Layers Together
So far we have seen that we can create layers and pass the output of one as the input of the next. Instead of creating intermediate tensors and passing them around, we can use `nn.Sequentual`, which does exactly that.

In [ ]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.6666, 0.5419],
         [0.6666, 0.5419],
         [0.6666, 0.5419]],

        [[0.6666, 0.5419],
         [0.6666, 0.5419],
         [0.6666, 0.5419]]], grad_fn=<SigmoidBackward0>)

### 3.5. Custom Modules

Instead of using the predefined modules, we can also build our own by extending the `nn.Module` class. For example, we can build a the `nn.Linear` (which also extends `nn.Module`) on our own using the tensor introduced earlier! We can also build new, more complex modules, such as a custom neural network. You will be practicing these in later lab sessions.

To create a custom module, the first thing we have to do is to extend the `nn.Module`. We can then initialize our parameters in the `__init__` function, starting with a call to the `__init__` function of the super class. All the class attributes we define which are `nn` module objects are treated as learnable objects, whose parameters can be learned during the training. Tensors are not parameters, but they can be turned into parameters if they are wrapped in `nn.Parameter` class.

All classes extending `nn.Module` are also expected to implement a `forward(x)` function, where `x` is a tensor. This is the function that is called when a parameter is passed to our module, such as in `model(x)`.

In [ ]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Define the structure of the model
    # There isn't anything specific about the naming of `self.model`. It could
    # be something arbitrary.
    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
    output = self.model(x)
    return output

Here is an alternative way to define the same class. You can see that we can replace `nn.Sequential` by defining the individual layers in the `__init__` method and connecting them in the `forward` method.

In [ ]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our layers
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

Now that we have defined our class, we can instantiate it and see what it does.

In [ ]:
# Make a sample input
input = torch.randn(2, 5)

# Create our model
model = MultilayerPerceptron(5, 3)

# Pass our input through our model
model(input)

tensor([[0.3433, 0.4674, 0.2672, 0.4508, 0.7274],
        [0.5467, 0.5104, 0.3409, 0.5293, 0.5685]], grad_fn=<SigmoidBackward0>)

We can inspect the parameters of our model with `named_parameters()` and `parameters()` methods.

In [ ]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[-0.4296, -0.4259,  0.1463,  0.0296, -0.2617],
          [-0.1804,  0.1300, -0.3800,  0.1008, -0.2596],
          [ 0.2071,  0.4198,  0.2219, -0.3306, -0.1561]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([-0.0926,  0.3940,  0.3873], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[-0.0422, -0.3976, -0.5342],
          [-0.5454,  0.1268, -0.4691],
          [-0.2284, -0.1960, -0.3195],
          [ 0.1121,  0.4527, -0.3794],
          [ 0.3747,  0.5017,  0.5577]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([ 0.2750,  0.4618, -0.4695,  0.0836, -0.0391], requires_grad=True))]

### 3.6. Example of Model Optimization
We have showed how gradients are calculated with the `backward()` function. Having the gradients isn't enough for our models to learn. We also need to know how to update the parameters of our models. This is where the optimizer comes in. `torch.optim` module contains several optimizers that we can use. Some popular examples are `optim.SGD` and `optim.Adam`. When initializing optimizers, we pass our model parameters, which can be accessed with `model.parameters()`, telling the optimizers which values it will be optimizing. Optimizer also has a learning rate (`lr`) parameter, which determines how big of an update will be made in every step. Different optimizers have different hyperparameters as well.

In [ ]:
import torch.optim as optim

After we have our optimization function, we can define a `loss` that we want to optimize for. We can either define the loss ourselves, or use one of the predefined loss function in `PyTorch`, such as `nn.BCELoss()`. Let's put everything together now! We will start by creating some dummy data.

In [ ]:
# Create the y data
y = torch.ones(10, 5)

# Add some noise to our goal y to generate our x
# We want out model to predict our original data, albeit the noise
x = y + torch.randn_like(y)
x

Now, we can define our model, optimizer and the loss function.

In [ ]:
# Instantiate the model
model = MultilayerPerceptron(5, 3)

# Define the optimizer
adam = optim.Adam(model.parameters(), lr=1e-1)

# Define loss using a predefined loss function
loss_function = nn.BCELoss() # Binary Cross Entropy Loss

# Calculate how our model is doing now
y_pred = model(x)
loss_function(y_pred, y).item()

Let's see if we can have our model achieve a smaller loss. Now that we have everything we need, we can setup our training loop.

In [ ]:
# Set the number of epoch, which determines the number of training iterations
n_epoch = 10

for epoch in range(n_epoch):
  # Set the gradients to 0
  adam.zero_grad()

  # Get the model predictions
  y_pred = model(x)

  # Get the loss
  loss = loss_function(y_pred, y)

  # Print stats
  print(f"Epoch {epoch}: traing loss: {loss}")

  # Compute the gradients
  loss.backward()

  # Take a step to optimize the weights
  adam.step()


In [ ]:
list(model.named_parameters())

You can see that our loss is decreasing. Let's check the predictions of our model now and see if they are close to our original `y`, which was all `1s`.

In [ ]:
# See how our model performs on the training data
with torch.no_grad():
    y_pred = model(x)
    print(y_pred)

In [ ]:
# Create test data and check how our model performs on it
x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

Great! Looks like our model almost perfectly learned to filter out the noise from the `x` that we passed in!

Optional demos for parameter initialization and dropout:
- [**He Initialization**](https://colab.research.google.com/drive/1HqxqOywHDsAuzRYiRtkWh3qESDIYoqIZ)
- [**Dropout**](https://colab.research.google.com/drive/1DWGfmCTlgXtV6sm0OgvBWc5Lsd2AuoQ6#scrollTo=JR3WeW4YJmnc)